# Generated by Django 2.2.16 on 2023-02-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230221_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created',
        ),
    ]
